const catchUserActionErrors = (e) =>{
    console.log("USER ERROR", e);
}
export {
    catchUserActionErrors
};